repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.4
    hooks:
      - id: ruff
        args: [--exit-non-zero-on-fix]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-merge-conflict
      - id: check-toml
      - id: name-tests-test
      - id: pretty-format-json

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        language: python
        types_or: [ python, pyi ]
        entry: mypy --ignore-missing-imports --implicit-reexport

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.0.1
    hooks:
      - id: pyupgrade
        args: [--py37-plus]
