[package]
name = "rust_http"
version = "0.1.0"
edition = "2021"

# Tell Cargo where your binary is:
[[bin]]
name = "rust_http"
path = "src/main.rs"

[dependencies]
actix-web = "4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
